version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Vilnius # Replace with your timezone
      - TZ=Europe/Vilnius # Replace with your timezone
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false # Set to true if using HTTPS
    volumes:
      - n8n_data:/home/node/.n8n
    command: start --tunnel

volumes:
  n8n_data:
